### PR TITLE
Add build instructions

### PR DESCRIPTION
**Pull request by igitur**
Add build instructions. I got these from a [forum post](https://www.heidisql.com/forum.php?t=24360).

### CODE REVIEW

**Comment by igitur** [comment]
Obviously few people have XE5, so I'm trying to build it in RAD Studio 10.2 Basic, which is free.  Looks like SynEdit is a bit outdated for a build in RS10.2. I'll upgrade and log a PR once I get a build working. If it works, it's probably best to include the components as git submodules.

I see madExcept is another dependency, right?

**Comment by ansgarbecker** [comment]
Yes, madExcept is required by heidisql.dpr, the main project file. But this is just downloaded and installed, unlike the other components.

**Comment by igitur** [comment]
Aaarrgh...

"Database components and drivers are not included." (in Delphi Starter)

**Comment by ansgarbecker** [comment]
Yes, you need the ADO connector, which is available in the Professional and Enterprise versions only.

**Comment by igitur** [comment]
Does Zeos depend on ADO Connector?

**Comment by ansgarbecker** [comment]
I don't know?

**Pull request merged**
