### PR TITLE
Added support for quoted identifiers and case-insensitive comparision…

### LINKED ISSUE #895: Autocompletion is case-sensitive with unquoted identifiers.
## Steps to reproduce this issue

1. Enter SQL, with a table\view that has one or more capital letters;
2. Try to get column list after `SELECT Table_Name.`;
3. Then I get... nothing

## Current behavior
After entering the dot, nothing happens

```sql
select
--  cfg.       -- The column list does not appear
    cfg.name
from
    pg_catalog.PG_CONFIG cfg
--  PG_CATALOG.pg_config cfg  -- Also does not work
--  PG_CATALOG.PG_CONFIG cfg  -- Also does not work
;
```

## Expected behavior
The appearance of the column selection list

## Possible solution
If the identifier is unquoted, then use `ilike` operator instead `=` or cast it to lowercase in SQL query to get the columns for the list, since in PostgreSQL all unquoted identifiers are stored in lowercase

## Environment

* **HeidiSQL version:** 
  
10.3.0.5877 (and earlier also)
* **Database system and version:** 
  
PostgreSQL 12.1
* **Operating system:** 
  
Windows 7 x64

### PR DESCRIPTION
**Pull request by zilzila**
… for not quoted identifiers for autocompletion and list of tables in table clauses. (Closes #895)

### CODE REVIEW

**Comment by zilzila** [comment]
**RegExp tests**
Field identifiers: https://regex101.com/r/jA7Qyr/1
Table identifiers: https://regex101.com/r/HcL3oR/1
Select table clauses between FROM and WHERE: https://regex101.com/r/ou5wxO/1
SQL Join type clauses: https://regex101.com/r/U8oeM5/1
SQL ON|USING clauses: https://regex101.com/r/1D5UPn/1

**Comment by ansgarbecker** [comment]
Quite large changes here. Did you test that all thoroughly?
At least the addition in TMainForm.ApplyVTFilter looks wrong, and unrelated. Please check that.

**Comment by zilzila** [comment]
> Quite large changes here.

Yep :) I think it will be a long story ...
>Did you test that all thoroughly?

Doing double check now.

> At least the addition in TMainForm.ApplyVTFilter looks wrong, and unrelated. Please check that.

Unrelated - I agree.
Just tired of seeing endless `ERegExpr` exceptions due to an empty expression, distract from debugging.
And what's the point of throwing an exception that is not handled with an empty expression? After all, nothing happens, does it? And if you do not throw an exception when the expression is empty, then this will not affect anything. I am wrong?

The comment on `rx.Exec ('abc')` was wrong, I agree with this, but I see no reason in throwing an exception with an empty expression anyway.
```pas
  try
    rx.Exec('abc');
  except
    on E:ERegExpr do begin
      if rx.Expression <> '' then begin
        LogSQL('Filter text is not a valid regular expression: "'+rx.Expression+'"', lcError);
        rx.Expression := '';
      end;
    end;
  end;
```

**Comment by ansgarbecker** [comment]
Yes I see your point, it's just that the exception may be thrown but does not add a log line if the expression is empty. However, when doing Delphi debugging, that's indeed an issue. So I'll merge the whole commit now and test it on PG, MSSQL and SQLite with other quote chars.
Btw, thanks a lot!

**Comment by zilzila** [comment]
Here is my test results.

Test configuration:
```sql
-- drop schema if exists Schema1 cascade;
-- drop schema if exists "Schema2" cascade;
create schema if not exists Schema1;
create schema if not exists "Schema2";

-- Schema 1
create table Schema1.Schema1Table1
(
    Schema1Table1Column1 int,
    "Schema1 Table1  -- ""Column2`` " int
);
create table Schema1."Schema1 Table2 ""quoted``"
(
    Schema1Table2Column1 int,
    "Schema1 Table2  -- ""Column2`` " int
);
create table Schema1."Schema1 Table3 -- !@#$%^&*:_+|\/ тест"
(
    Schema1_Table3_Column1 int,
    "Schema1 Table3  -- ""Column2`` " int
);

-- Schema 2
create table "Schema2".Schema2Table1
(
    Schema2Table1Column1 int,
    "Schema2 Table1  -- ""Column2`` " int
);
create table "Schema2"."Schema2 Table2 ""quoted``"
(
    Schema2Table2Column1 int,
    "Schema2 Table2  -- ""Column2`` " int
);
create table "Schema2"."Schema2 Table3 -- !@#$%^&*:_+|\/ тест"
(
    Schema2_Table3_Column1 int,
    "Schema2 Table3  -- ""Column2`` " int
);
```

Tests:
```sql
select ;
select @@session.;

-- FieldIdent tests ---------------------------
-- Pick root of the connection -> no schema selected (optional)
-- Explicit schema
select Schema1.;
select Schema1.Schema1Table1.;
select Schema1."Schema1 Table2 ""quoted``".;
select Schema1."Schema1 Table3 -- !@#$%^&*:_+|\/ тест".;

select "Schema2".;
select "Schema2".Schema2Table1.;
select "Schema2"."Schema2 Table2 ""quoted``".;
select "Schema2"."Schema2 Table3 -- !@#$%^&*:_+|\/ тест".;

-- Pick schema1 (unquoted) in DBTree
-- Implicit unquoted schema
select Schema1Table1.;
select "Schema1 Table2 ""quoted``".;
select "Schema1 Table3 -- !@#$%^&*:_+|\/ тест".;

-- Pick schema2 (quoted) in DBTree
-- Implicit quoted schema
-- Tables do not work when using an implicit quoted schema
select Schema2Table1.;
select "Schema2 Table2 ""quoted``".;
select "Schema2 Table3 -- !@#$%^&*:_+|\/ тест".;


-- TableIdent tests ---------------------------
select * from  ;
select * from  Schema1.;

-- Alias (unquoted) (without AS)
-- Pick root of the connection -> no schema selected (optional)
-- Explicit unquoted schema
select S1t1. from  Schema1.Schema1Table1  S1t1;
select S1t1. from  Schema1."Schema1 Table2 ""quoted``"  S1t1;
select S1t1. from  Schema1."Schema1 Table3 -- !@#$%^&*:_+|\/ тест"  S1t1;

-- Pick schema1 (unquoted) in DBTree
-- Implicit unquoted schema
select S1t1. from  Schema1Table1  S1t1;
select S1t1. from  "Schema1 Table2 ""quoted``"  S1t1;
select S1t1. from  "Schema1 Table3 -- !@#$%^&*:_+|\/ тест"  S1t1;


-- Alias (unquoted) (with AS)
-- Pick root of the connection -> no schema selected (optional)
-- Explicit unquoted schema
select S1t1. from  Schema1.Schema1Table1  as  S1t1;
select S1t1. from  Schema1."Schema1 Table2 ""quoted``"  as  S1t1;
select S1t1. from  Schema1."Schema1 Table3 -- !@#$%^&*:_+|\/ тест"  as  S1t1;

-- Pick schema1 (unquoted) in DBTree
-- Implicit unquoted schema
select S1t1. from  Schema1Table1  as  S1t1;
select S1t1. from  "Schema1 Table2 ""quoted``"  as  S1t1;
select S1t1. from  "Schema1 Table3 -- !@#$%^&*:_+|\/ тест"  as  S1t1;


-- Alias (quoted) (without AS)
-- Pick root of the connection -> no schema selected (optional)
-- Explicit unquoted schema
select "S1t1". from  Schema1.Schema1Table1  "S1t1";
select "S1t1". from  Schema1."Schema1 Table2 ""quoted``"  "S1t1";
select "S1t1". from  Schema1."Schema1 Table3 -- !@#$%^&*:_+|\/ тест"  "S1t1";
-- Does not work. Correct.
select S1t1. from  Schema1.Schema1Table1  "S1t1";


-- Pick schema1 (unquoted) in DBTree
-- Implicit unquoted schema
select "S1t1". from  Schema1Table1  "S1t1";
select "S1t1". from  "Schema1 Table2 ""quoted``"  "S1t1";
select "S1t1". from  "Schema1 Table3 -- !@#$%^&*:_+|\/ тест"  "S1t1";
-- Does not work. Correct.
select S1t1. from  Schema1Table1  "S1t1";


-- Alias (quoted) (with AS)
-- Pick root of the connection -> no schema selected (optional)
-- Explicit unquoted schema
select "S1t1". from  Schema1.Schema1Table1  as  "S1t1";
select "S1t1". from  Schema1."Schema1 Table2 ""quoted``"  as  "S1t1";
select "S1t1". from  Schema1."Schema1 Table3 -- !@#$%^&*:_+|\/ тест"  as  "S1t1";
-- Does not work. Correct.
select S1t1. from  Schema1.Schema1Table1  as  "S1t1";

-- Pick schema1 (unquoted) in DBTree
-- Implicit unquoted schema
select "S1t1". from  Schema1Table1  as  "S1t1";
select "S1t1". from  "Schema1 Table2 ""quoted``"  as  "S1t1";
select "S1t1". from  "Schema1 Table3 -- !@#$%^&*:_+|\/ тест"  as  "S1t1";
-- Does not work. Correct.
select S1t1. from  Schema1.Schema1Table1  as  "S1t1";


-- Alias (quoted) (with AS) (no spaces)
-- Even like this!
select "S1t1". from  "Schema1 Table2 ""quoted``"as  "S1t1";
select "S1t1". from  "Schema1 Table2 ""quoted``"  as"S1t1";
select "S1t1". from  "Schema1 Table2 ""quoted``"as"S1t1";
```
Broken identifiers
```sql
create schema "Schema broken";
create schema "Schema""broken``";
create table schema1."Broken'Table" (id int);
create table schema1."Broken(Table" (id int);
create table schema1."Broken)Table" (id int);
```
Conclusion:
Quoted schema does not work.
Some characters in quoted identifiers `'`, `(`, `)` are deleted or duplicated during processing -> broken.

**Comment by ansgarbecker** [comment]
Please have a look at #917 - there must be something more broken than these (edge) cases.

**Pull request merged**
