### PR TITLE
Save to file

### PR DESCRIPTION
**Pull request by JaviPlaya**
See this link to know more.

https://www.heidisql.com/forum.php?t=36024

### CODE REVIEW

**Comment by ansgarbecker** [comment]
I'm sorry, but you should have discussed such huge changes with me previously. I won't accept pull request which do not reference an issue here, where I had the chance to discuss the idea.

**Comment by JaviPlaya** [comment]
Sorry, I'm new to this whole world of contributing to projects.
Sorry, I have to learn from mistakes.
Can you tell me what is the correct way? Thank you. And sorry for wasting your time on a newbie.

**Comment by ansgarbecker** [comment]
Well, you need to refer to some ticket here on Github, not to a forum thread. In this case, I was not really convinced of the idea, so there was a need to go deeper into it. Sorry but if I would accept all of such changes, HeidiSQL would be blown up with controls and whatever things. I want to keep HeidiSQL as easy as it can be, without adding too much things which are not used by the majority of users. I'm also sorry for the time you have put into it, but I'm still not thinking this is something for all users.

**Comment by JaviPlaya** [comment]
Thanks for answering.

I understand the philosophy you are trying to maintain with your great program, I understand and respect it. And I must admit that you are right, my modification is not useful for a large number of users.

If you ever find my suggestion useful, remember this newbie.

When you do something you like, it is never wasted time. Thanks for wasting your time with me.

**Pull request closed without merging**
