### PR TITLE
Fix and improve exporting in PHP format

### PR DESCRIPTION
**Pull request by mlocati**
In PHP we have two kind of strings (well, excluding heredoc/nowdoc strings):

- single-quoted strings (eg `'Hi there'`)
- double-quoted strings (eg `"Hi there"`)

They behave very differently:
- single-quoted strings can't contain special character sequences (except `\'` and `\\`)
- double-quoted strings can contain sequences (for example `\n`), as well as variables ([example](https://3v4l.org/K6SEY))

This, for example, implies that we have to "escape" the `$` in double quoted strings, otherwise we break the strings (and possibly the execution - [example](https://3v4l.org/tIDmS)).

Furthermore, since PHP 5.4 (which is 12 years old), PHP supports the compact `[...]` notation for arrays (instead of the more verbose `array(...)`).

Finally, accordingly to the PSR-2 (PHP Standard Recommendation # 2), NULL values should be written in lower case ([see here](https://www.php-fig.org/psr/psr-2/#25-keywords-and-truefalsenull)).

So, we can't really use the same function to generate JSON and PHP strings.

In this PR I renamed the old `FormatPhp` function to `FormatJson`, and implemented a new `FormatPhp` function that:
- exports strings in single-quote format, if possible
- escapes more characters if the double-quote format is used

PS: I don't have Delphi, so I didn't test anything (and it has been 3 decades since the last time I wrote some Pascal code 😉) - so please check that everything works as expected.

### CODE REVIEW

**Comment by mlocati** [comment]
@ansgarbecker any reason for holding this PR back? Do you need more details?

**Comment by ansgarbecker** [comment]
@mlocati I'm normally not accepting pull requests, due to some bad experiences in the past. There seems to be a conflict due to a modification from myself in the same file, and I have no experience with resolving conflicts in the web editor or command line. But I will try to solve that.

**Comment by ansgarbecker** [comment]
Somehow I managed to merge your commit into the master branch. But in the git log it's a catastrophe - a merge commit with many unrelated changes done again.

**Comment by mlocati** [comment]
I don't see anything strange, it's just a normal merge commit...

immagine

**Comment by mlocati** [comment]
The result is just commit eb4820552854dfd6e5c5a41d304e7130f7828322 which comes right after 21ab7c89174f6601259cce2b0966b2f003895cd7 in the `master` branch (and that commit eb4820552854dfd6e5c5a41d304e7130f7828322 contains the changes I suggested in this #1950).

**Comment by ansgarbecker** [comment]
Yes looks probably better than I thought.

Is there a reason in `FormatPhp()` for preferring the effort with escaping within double quotes, instead of always using single quotes?

**Comment by mlocati** [comment]
Single quoted strings can't contain special characters.

Let's say for example you want to export the newline character: the only way to do that is to write it as is:

```php
'First line
second line'
```

In double quoted strings we can instead use `\n`:

```php
"First line\nsecond line"
```

And I think i'ts much more readable to have

```php
$table = [
    [
        'id' => 1,
        'field' => "First line\nsecond line",
    ],
    [
        'id' => 2,
        'field' => "First line\nsecond line",
    ],
];
```

if compared to

```php
$table = [
    [
        'id' => 1,
        'field' => "First line
second line",
    ],
    [
        'id' => 2,
        'field' => "First line
second line",
    ],
];
```

**Comment by ansgarbecker** [comment]
Ok then readability in one line was the goal. Thanks!

**Comment by mlocati** [comment]
Thanks to you!!!

**Pull request merged**
